services:
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
      - 18000:18000
    volumes:
      - .:/home/jovyan/work
    user: root
    command: start-notebook.py --NotebookApp.token=''
